VSharp-team/VSharp

VSharp.SILI/ControlFlow.fs, VSharp.SILI/Interpreter.fs, VSharp.SILI/SVM.fs, VSharp.SILI/Transformations.fs
Loop is now rewritten to more compact representation.
Work with implicit PathCondition in reduceBlockStatement is started
WARNING: types temporary were made less general
=> Some critical fixes for interpreter

VSharp.CSharpUtils/Tests/ClassesSimple.cs, VSharp.SILI/CallGraph.fs, VSharp.SILI/ControlFlow.fs, VSharp.SILI/DecompilerServices.fs, VSharp.SILI/Functions.fs, VSharp.SILI/Interpreter.fs, VSharp.SILI/SVM.fs, VSharp.SILI/State.fs, VSharp.SILI/Terms.fs
+ Rollback does not exist any more
+ Unbounded encoding is now performed via regular SVM-call (infrastructurally)
=> Epic refactoring, stage III: infrastructural simplification of unbounded recursion encoding

VSharp.CSharpUtils/Tests/ClassesSimple.cs, VSharp.SILI/Array.fs, VSharp.SILI/Common.fs, VSharp.SILI/Interpreter.fs, VSharp.SILI/Memory.fs, VSharp.SILI/State.fs, VSharp.SILI/Terms.fs, VSharp.Test/Tests/VSharp.CSharpUtils/Unix.gold, VSharp.Test/Tests/VSharp.CSharpUtils/Win32NT.gold
+ SymbolicConstantSource is now .NET class with private inheritors  in separate modules
+ makeSymbolicInstance, defaultOf moved back to Memory.fs
+ makeSymbolicArray, arrayLength, etc. moved back to Array.fs
Signed-off-by: Dmitry Mordvinov <dvvsrd@gmail.com>
=> Cleaning up internal dependencies

VSharp.CSharpUtils/Tests/ClassesSimple.cs, VSharp.CSharpUtils/Tests/Typecast.cs, VSharp.SILI/Arithmetics.fs, VSharp.SILI/Common.fs, VSharp.SILI/ControlFlow.fs, VSharp.SILI/Extern/SDK.fs, VSharp.SILI/Extern/System/Math.fs, VSharp.SILI/Functions.fs, VSharp.SILI/Interpreter.fs, VSharp.SILI/Memory.fs, VSharp.SILI/Operations.fs, VSharp.SILI/Operators.fs, VSharp.SILI/Pointers.fs, VSharp.SILI/Propositional.fs, VSharp.SILI/State.fs, VSharp.SILI/Terms.fs, VSharp.SILI/Types.fs, VSharp.SILI/VSharp.SILI.fsproj, VSharp.Utils/Hierarchy.fs
+ pointer comparison moved to Pointers.fs
+ generic unary and binary operations on terms are now in Operators.fs
+ term metadata now contains storage for miscellanious data
+ lazy instantiation source now can be top level address of the
heap reference
+ 'this' renamed to 'x' all over the codebase
Signed-off-by: Dmitry Mordvinov <dvvsrd@gmail.com>
=> Small refactoring for operators subsystem

VSharp.SILI.Core/Database.fs, VSharp.SILI.Core/InterpreterBase.fs, VSharp.SILI.Core/Memory.fs, VSharp.SILI.Core/Terms.fs, VSharp.SILI/CFA.fs, VSharp.SILI/Instruction.fs, VSharp.SILI/Interpreter.fs, VSharp.Test/Golds/VSharp/Test/Tests/PDR/DoubleInitializeObjects.-51226744.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/MultipleInitializeStaticFieldsInCfa.-202758858.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/NewObjInLoop.-51226744.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/NewObjInLoop1.-51226744.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/SameN.383462754.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestAllocatedType_1.-2039345157.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestAllocatedType_2.-2039345157.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestAllocatedType_3.-2039345157.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestAllocatedType_4.-1339916414.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestConcreteArray.-202758858.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestForCycle_5x.-202758858.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestLengths_1.-2039345157.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestLengths_2.-2039345157.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestLengths_3.-2039345157.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestLengths_4.-2039345157.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestLengths_5.-2039345157.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestLowerBound_1.-2039345157.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestLowerBound_2.-1339916414.gold, VSharp.Test/Golds/VSharp/Test/Tests/PDR/TestPopStackWithReservedVariable.-2039345157.gold, VSharp.Test/Tests/PDR.cs, VSharp.Utils/MappedStack.fs
Future improvements: dominators should calculcated for gaining right sets of Allocated Types, Array Lengths and ArrayLowerBounds (named **Sets**). Currently, when execution goes to vertex with different **Sets** new vertex is created. Exception is vertices inside cycle (Such vertices are hacked to be visited only once with unique operationalStack for cfa-construction termination).
=> Allocated Types, Array Lengths, Array LowerBounds are global for cfa-construction

VSharp.SILI/Searcher.fs, VSharp.SILI/TargetedSearcher.fs
Weighted searcher cannot add suspended a stated to storage, but the state is mutable, and it can be made suspended when it is already in storage. When guided searcher picks a state from its base searcher (and it is a weighted searcher), it can make it suspended, but the state remains in storage and is picked again and again infinitely. As a result, some tests fall into infinite recursion.
How to reproduce: run test `ForSimple` with `SearchStrategy.ShortestDistance`
=> [fix] Suspended states are infinitely picked in guided mode with weighted searcher

VSharp.InternalCalls/String.fs, VSharp.SILI.Core/API.fs, VSharp.SILI.Core/ArrayInitialization.fs, VSharp.SILI.Core/ConcreteMemory.fs, VSharp.SILI.Core/Copying.fs, VSharp.SILI.Core/Memory.fs, VSharp.SILI.Core/State.fs, VSharp.SILI/TestGenerator.fs, VSharp.Test/IntegrationTests.cs, VSharp.Test/Tests/LoanExam/CreditCalculator.cs, VSharp.Utils/Collections.fs, VSharp.Utils/MemoryGraph.fs, VSharp.Utils/Reflection.fs, VSharp.Utils/TypeUtils.fs
- added IConcreteMemory interface
- implemented deep copy for concrete memory
- state fork uses concrete memory deep copy
- fixed string internal calls: constructor of char array
- style fixes
- TODO: string constructor of char array creates new string instance, but if char array is null, it should return empty string, which is interned and may be already allocated, so in this case constructor should return existing reference
=> Fixes for concrete memory

VSharp.SILI.Core/API.fs, VSharp.SILI.Core/API.fsi, VSharp.SILI.Core/CallStack.fs, VSharp.SILI.Core/Memory.fs, VSharp.SILI.Core/Terms.fs, VSharp.SILI/CILState.fs, VSharp.SILI/Interpreter.fs, VSharp.SILI/SILI.fs, VSharp.SILI/TestGenerator.fs, VSharp.Test/IntegrationTests.cs, VSharp.Test/Tests/Byrefs.cs, VSharp.Test/Tests/Structs.cs, VSharp.Utils/TestResultsChecker.fs
- For struct methods, allocate this on additional stack frame, struct methods can be explored without IIE
- Allocate byref parameters on additional stack frame, methods with byref parameters can be explored
=> [fix] Allocate value-type this and byref parameters on stack

VSharp.SILI.Core/ConcreteMemory.fs, VSharp.SILI.Core/PathCondition.fs, VSharp.SILI/Statistics.fs
- Fix appeared false PC-s with multiple elements
- Fix copying System.Type objects, causing inconsistent CLR state with access violation
- Fix duplicate errors reported (tested with JB Lifetimes.Collections -- 177 errors vs 134)
=> [fix] PC, deep copy and error stats fixes

VSharp.API/VSharp.cs, VSharp.CSharpUtils/ReflectionUtils.cs, VSharp.Runner/RunnerProgram.cs, VSharp.SILI/BidirectionalSearcher.fs, VSharp.SILI/CILState.fs, VSharp.SILI/CombinedWeighter.fs, VSharp.SILI/ConcolicSearcher.fs, VSharp.SILI/ContributedCoverageSearcher.fs, VSharp.SILI/DFSSortedByContributedCoverageSearcher.fs, VSharp.SILI/FairSearcher.fs, VSharp.SILI/InterleavedSearcher.fs, VSharp.SILI/Interpreter.fs, VSharp.SILI/Options.fs, VSharp.SILI/SILI.fs, VSharp.SILI/Searcher.fs, VSharp.SILI/Statistics.fs, VSharp.SILI/TargetedSearcher.fs, VSharp.SILI/VSharp.SILI.fsproj, VSharp.Solver/Z3.fs, VSharp.Test/IntegrationTests.cs, VSharp.Test/Tests/LoanExam/CreditCalculator.cs, VSharp.Utils/DiscretePDF.fs, VSharp.Utils/PriorityCollection.fs
- Make SILI work with multiple methods simultaneously: entry point states are added to the same searcher
- Add Pick method with selector function to IForwardSearcher
- Add new fair searcher, which shares execution between different methods according to given timeout
=> [feat] Fair multimethod searcher

VSharp.API/VSharp.cs, VSharp.SILI/Options.fs, VSharp.SILI/SILI.fs, VSharp.Test/IntegrationTests.cs, VSharp.Test/Tests/LinqTest.cs
A simple check of coverage to stop SILI when there is nothing more to cover. 
- However, theoretically, it can overapproximate and consider blocks which threw exception as covered. @gsvgit 's https://github.com/VSharp-team/VSharp/pull/15 should fix this bug
- For multiple methods complete coverage is checked, but in fact a more fine-grained check can be done to exclude particular methods from searcher
@MchKosticyn We need to check that this fixes the problem with recursive test
=> Stop SILI when 100% coverage is achieved

.github/workflows/integration_tests.yml, .github/workflows/publish_docker.yml, docker/Dockerfile_runner_cli
Add new GitHub actions pipeline which runs integration tests on push to master and publishes Docker image with V# runner to packages
=> Add Docker image publishing for UTBot integration

VSharp.InternalCalls/Buffer.fs, VSharp.Runner/RunnerProgram.cs, VSharp.SILI.Core/API.fs, VSharp.SILI.Core/ArrayInitialization.fs, VSharp.SILI.Core/ConcreteMemory.fs, VSharp.SILI.Core/Memory.fs, VSharp.SILI/FairSearcher.fs, VSharp.SILI/Searcher.fs, VSharp.SILI/Statistics.fs, VSharp.Solver/Z3.fs, VSharp.TestRenderer/CodeRenderer.cs, VSharp.Utils/Collections.fs, VSharp.Utils/Mocking.fs, VSharp.Utils/UnitTest.fs
- fixed https://github.com/VSharp-team/VSharp/issues/223
- fixed efficiency for getting all indices of array and all indices of array with values
- fixed 'Memmove' internal call
- fixed decoding of stack reading constant
- fixed '--namespace' console command (exploring all underlying namespaces)
- fixed searcher initialization
=> Stabilization and fixes for Lifetimes benchmarks

VSharp.API/VSharp.cs, VSharp.IL/CFG.fs, VSharp.IL/CallGraph.fs, VSharp.IL/DotVisualizer.fs, VSharp.Runner/RunnerProgram.cs, VSharp.SILI/CILState.fs, VSharp.SILI/DistanceWeighter.fs, VSharp.SILI/FairSearcher.fs, VSharp.SILI/Interpreter.fs, VSharp.SILI/SILI.fs, VSharp.SILI/Statistics.fs, VSharp.SILI/TargetedSearcher.fs, VSharp.Solver/SolverPool.fs, VSharp.Solver/Z3.fs, VSharp.Test/IntegrationTests.cs, VSharp.Test/Tests/LoanExam.cs, VSharp.Test/Tests/RecursiveObjects.cs, VSharp.TestExtensions/ObjectsComparer.cs, VSharp.TestRenderer/RendererTool.cs, VSharp.TestRenderer/TestsRenderer.cs, VSharp.TestRunner/TestRunnerProgram.cs, VSharp.Utils/Logger.fs
- Add ability to add tags to logs for state transitions debugging convenience
- Fix paused states not filtered in Guided Searcher
- Fix inefficient block coverage info extraction
- Remove different types of coverage (ByTest and ByEntryPointTest)
LoanExam is fully covered in less than 10 seconds with guided mode disabled (like it was before FairSearcher), with guided its still covered worse
=> LoanExam test regress fixes

VSharp.API/VSharp.cs, VSharp.Runner/RunnerProgram.cs, VSharp.Test/IntegrationTests.cs, VSharp.Test/Tests/Generic.cs, VSharp.Utils/MemoryGraph.fs, VSharp.Utils/Reflection.fs, VSharp.Utils/UnitTest.fs
Use recursive XML nodes to represent generic arguments instead of fully qualified type name (because of some issues with getting types by fully qualified name)
Fixes issue https://github.com/VSharp-team/VSharp/issues/193
**Merge after https://github.com/VSharp-team/VSharp/pull/213https://github.com/VSharp-team/VSharp/pull/213**
=> Serialize generic arguments as recursive xml nodes

VSharp.InternalCalls/Loader.fs, VSharp.Runner/RunnerProgram.cs, VSharp.SILI.Core/API.fs, VSharp.SILI.Core/API.fsi, VSharp.SILI.Core/Memory.fs, VSharp.SILI.Core/MemoryRegion.fs, VSharp.SILI/SILI.fs, VSharp.SILI/TestGenerator.fs, VSharp.Solver/Z3.fs, VSharp.Test/Tests/Lists.cs, VSharp.TestExtensions/Allocator.cs, VSharp.TestRenderer/CodeRenderer.cs, VSharp.TestRenderer/MethodRenderer.cs, VSharp.TestRenderer/TestsRenderer.cs, VSharp.Utils/MemoryGraph.fs, VSharp.Utils/Reflection.fs, VSharp.Utils/UnitTest.fs
- fixed calling non-public methods or methods of non-public type (https://github.com/VSharp-team/VSharp/issues/233)
- fixed deserialization of compact arrays
- command `--public-method-of-class` renamed to `--type`
=> Stabilization: part VI

VSharp.CSharpUtils/ReflectionUtils.cs, VSharp.IL/CFG.fs, VSharp.InternalCalls/Loader.fs, VSharp.InternalCalls/Runtime.CompilerServices.RuntimeHelpers.fs, VSharp.InternalCalls/Runtime.CompilerServices.RuntimeHelpers.fsi, VSharp.InternalCalls/Span.fs, VSharp.InternalCalls/Thread.fs, VSharp.InternalCalls/Thread.fsi, VSharp.InternalCalls/Unsafe.fs, VSharp.InternalCalls/Unsafe.fsi, VSharp.SILI.Core/ConcreteMemory.fs, VSharp.SILI.Core/Memory.fs, VSharp.SILI.Core/SolverInteraction.fs, VSharp.SILI.Core/State.fs, VSharp.SILI.Core/TypeSolver.fs, VSharp.SILI/Interpreter.fs, VSharp.Solver/Z3.fs, VSharp.Test/Tests/LinqTest.cs, VSharp.Test/Tests/Lists.cs, VSharp.TestExtensions/Allocator.cs, VSharp.TestRenderer/CodeRenderer.cs, VSharp.TestRenderer/MethodRenderer.cs, VSharp.TestRenderer/RendererTool.cs, VSharp.Utils/TypeUtils.fs, VSharp.Utils/WeakDictionary.fs
- fixed decoding: supported lambda predicate case
- fixed renrerer
- fixed 'isPublic' predicate
- fixed CFG: DFS rewritten in CPS
- fixed concrete memory: unsafe reading, allocating boxed locations
- added internal calls
- fixed test extension 'Allocator'
- fixed type solver and SMT solver interaction
=> Stabilization: part XIV

VSharp.SILI.Core/State.fs, VSharp.SILI.Core/TypeSolver.fs, VSharp.Test/Tests/Lists.cs, VSharp.Utils/TypeUtils.fs
Add `candidates` data structure in order to rank types and not to truncate mock.
=> Type solver improvement

VSharp.Explorer/Explorer.fs, VSharp.Explorer/Statistics.fs, VSharp.SILI/InstructionPointer.fs, VSharp.SILI/Interpreter.fs, VSharp.Test/Tests/Arithmetics.cs
Particularly, fixes incorrect coverage in ExceptionThrownInFilter test
=> Consider calls covered only on return

VSharp.SILI.Core/API.fs, VSharp.SILI.Core/API.fsi, VSharp.SILI.Core/Arithmetics.fs, VSharp.SILI.Core/Operations.fs, VSharp.SILI/Interpreter.fs, VSharp.Solver/Z3.fs, VSharp.Test/Tests/Arithmetics.cs, VSharp.Utils/TypeUtils.fs
Overflow check in numeric operations implemented via Z3 "no-ovf" functions
=> Fixed overflow check
