VSharp.SILI/SVM.fs

Signed-off-by: misonijnik <misonijnik@gmail.com>

Disabled symbolic execution of abstract methods

---

VSharp.CSharpUtils/Tests/Typecast.cs
VSharp.SILI/Interpreter.fs
VSharp.SILI/Types.fs
VSharp.Test/Tests/VSharp.CSharpUtils/Unix.gold
VSharp.Test/Tests/VSharp.CSharpUtils/Win32NT.gold

- upgraded reduceTypeCastExpression and reduceTryCastExpression;
- fixed bugs in operator "is";
- add new tests for typecast and trycast.

Symbolic types, stage II

---

VSharp.SILI/Arithmetics.fs
VSharp.SILI/Array.fs
VSharp.SILI/CallGraph.fs
VSharp.SILI/Common.fs
VSharp.SILI/ControlFlow.fs
VSharp.SILI/DecompilerServices.fs
VSharp.SILI/Extern/SDK.fs
VSharp.SILI/Extern/System/Environment.fs
VSharp.SILI/Extern/System/Math.fs
VSharp.SILI/Extern/System/SystemArray.fs
VSharp.SILI/Functions.fs
VSharp.SILI/Interpreter.fs
VSharp.SILI/Memory.fs
VSharp.SILI/Merging.fs
VSharp.SILI/Propositional.fs
VSharp.SILI/SVM.fs
VSharp.SILI/State.fs
VSharp.SILI/Strings.fs
VSharp.SILI/Terms.fs
VSharp.SILI/Types.fs
VSharp.SILI/VSharp.SILI.fsproj
VSharp.Utils/Prelude.fs

Terms are now binded to its origin (IL-instruction and stack trace)

Epic refactoring, stage IV.II: term bindings to IL-code

---

VSharp.CSharpUtils/Tests/Conditional.cs
VSharp.SILI/ControlFlow.fs
VSharp.SILI/Extern/System/SystemArray.fs
VSharp.SILI/Interpreter.fs
VSharp.SILI/Memory.fs
VSharp.SILI/Merging.fs
VSharp.Test/Tests/VSharp.CSharpUtils/Unix.gold
VSharp.Test/Tests/VSharp.CSharpUtils/Win32NT.gold
VSharp.Utils/Cps.fs

Refactored reduceConditionalExecution and reduceConditionalExpression;
Added k-version map-functions from Merging.fs.

Fixed bug in reduceConditionalExecution (handled exceptions in condition)

---

VSharp.SILI/CallGraph.fs
VSharp.SILI/Extern/SDK.fs
VSharp.SILI/Extern/System/Environment.fs
VSharp.SILI/Extern/System/Environment.fsi
VSharp.SILI/Extern/System/Math.fs
VSharp.SILI/Extern/System/Math.fsi
VSharp.SILI/Extern/System/String.fs
VSharp.SILI/Extern/System/String.fsi
VSharp.SILI/Extern/System/SystemArray.fs
VSharp.SILI/Extern/System/SystemArray.fsi
VSharp.SILI/Functions.fs
VSharp.SILI/Interpreter.fs
VSharp.SILI/Memory.fs
VSharp.SILI/State.fs
VSharp.SILI/VSharp.SILI.fsproj
VSharp.SILI/packages.config

State refactoring

---

VSharp.SILI/Arrays.fs
VSharp.SILI/Operators.fs

- added reference equality
- added refToInt functon
- added functions to create concrete or symbolic array

References equality and helpers for arrays

---

VSharp.SILI/Interpreter.fs
VSharp.SILI/Memory.fs
VSharp.Utils/Collections.fs
VSharp.Utils/MappedStack.fs

- Improved Collections
- Changed `changeLast` due to [comment](https://github.com/dvvrd/VSharp/pull/51#discussion_r155917070) in @miha2733 pull request

Style fixes

---

VSharp.SILI/Arrays.fs
VSharp.SILI/Common.fs
VSharp.SILI/Memory.fs
VSharp.SILI/Terms.fs
VSharp.Test/Tests/VSharp.CSharpUtils/Unix.gold
VSharp.Utils/Prelude.fs

Constants are now compared by source instead of name.

Constants comparison improvement

---

VSharp.SILI.Core/API.fs
VSharp.SILI.Core/API.fsi
VSharp.SILI.Core/Arithmetics.fs
VSharp.SILI.Core/Arrays.fs
VSharp.SILI.Core/Common.fs
VSharp.SILI.Core/ControlFlow.fs
VSharp.SILI.Core/Explorer.fs
VSharp.SILI.Core/Lambdas.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/Merging.fs
VSharp.SILI.Core/Operators.fs
VSharp.SILI.Core/Pointers.fs
VSharp.SILI.Core/Propositional.fs
VSharp.SILI.Core/State.fs
VSharp.SILI.Core/Strings.fs
VSharp.SILI.Core/Terms.fs
VSharp.SILI.Core/TypeCasting.fs
VSharp.SILI.Core/Types.fs
VSharp.SILI.Core/VSharp.SILI.Core.fsproj
VSharp.SILI/Functions.fs
VSharp.SILI/Interpreter.fs
VSharp.SILI/MetadataTypes.fs
VSharp.SILI/Transformations.fs
VSharp.Utils/Prelude.fs

+ Types module in backend made internal
+ All module functions are now named in camelcase
+ Added interface file for API

More improvement for codebase

---

VSharp.SILI.Core/API.fs
VSharp.SILI.Core/Common.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/Operators.fs
VSharp.SILI.Core/TypeCasting.fs
VSharp.Test/Tests/VSharp.CSharpUtils/Unix.gold

- [refactor] simpleConditionalExecution -> statelessConditionalExecution
- [refactor] reduceConditionalExecution -> statedConditionalExecution
- error message was fixed
- instantiators merging was fixed

Tiny fixes and refactoring

---

VSharp.SILI.Core/API.fs
VSharp.SILI.Core/API.fsi
VSharp.SILI.Core/Arrays.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI/Extern/System/Environment.fs
VSharp.SILI/Extern/System/Environment.fsi
VSharp.SILI/Extern/System/Math.fs
VSharp.SILI/Extern/System/Math.fsi
VSharp.SILI/Extern/System/String.fs
VSharp.SILI/Extern/System/String.fsi
VSharp.SILI/Extern/System/SystemArray.fs
VSharp.SILI/Extern/System/SystemArray.fsi
VSharp.SILI/Extern/System/Thread.fs
VSharp.SILI/Extern/System/Thread.fsi
VSharp.SILI/Interpreter.fs
VSharp.SILI/VSharp.SILI.fsproj

- NullCoalescing function was implemented
- Extern methods getDomain and getFastDomain was added
- Improved style

Small style fixes, null coalescing and getDomain

---

VSharp.SILI.Core/API.fs
VSharp.SILI.Core/API.fsi
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/Operators.fs
VSharp.SILI.Core/Pointers.fs
VSharp.SILI.Core/State.fs
VSharp.SILI.Core/Strings.fs
VSharp.SILI.Core/Terms.fs
VSharp.SILI.Core/Types.fs
VSharp.SILI/Extern/System/Environment.fs
VSharp.SILI/Interpreter.fs
VSharp.Test/Tests/VSharp.CSharpUtils/Unix.gold
VSharp.Test/Tests/VSharp.CSharpUtils/Win32NT.gold

- String term type was deleted
- Alias for string type was added (ClassType of String)
- helpful function were added

String type changed to string alias

---

VSharp.CSharpUtils/Tests/Method.cs
VSharp.SILI/Interpreter.fs
VSharp.Test/Tests/VSharp.CSharpUtils/Unix.gold
VSharp.Test/Tests/VSharp.CSharpUtils/Win32NT.gold

Add more tests for symbolic VMT.
Signed-off-by: misonijnik <misonijnik@gmail.com>

Fixed style and bug in symbolic VMT.

---

VSharp.SILI.Core/API.fs
VSharp.SILI.Core/Arrays.fs
VSharp.SILI.Core/Common.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/Merging.fs
VSharp.SILI.Core/Pointers.fs
VSharp.SILI.Core/State.fs
VSharp.SILI.Core/Strings.fs
VSharp.SILI.Core/Terms.fs
VSharp.SILI/Interpreter.fs
VSharp.Test/SiliTests.cs
VSharp.Test/Tests/VSharp.CSharpUtils/Unix.gold
VSharp.Test/Tests/VSharp.CSharpUtils/Win32NT.gold
VSharp.Utils/Heap.fs
VSharp.Utils/Prelude.fs

- Merge uses read from heap location

Amazing Refactoring: Stage III

---

VSharp.SILI.Core/Arrays.fs
VSharp.SILI.Core/ControlFlow.fs
VSharp.SILI.Core/Explorer.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/Merging.fs
VSharp.SILI.Core/Pointers.fs
VSharp.SILI.Core/Substitution.fs
VSharp.SILI.Core/Terms.fs
VSharp.SILI.Core/TypeCasting.fs
VSharp.SILI.Core/Types.fs
VSharp.SILI/DecompilerServices.fs
VSharp.SILI/Functions.fs
VSharp.SILI/Interpreter.fs
VSharp.SILI/MetadataTypes.fs
VSharp.SILI/Transformations.fs
VSharp.Test/Tests/VSharp.CSharpUtils/Unix.gold
VSharp.Test/Tests/VSharp.CSharpUtils/Win32NT.gold
VSharp.Utils/Collections.fs

Small fixes for NeverUnroll

---

VSharp.SILI.Core/API.fs
VSharp.SILI.Core/API.fsi
VSharp.SILI/CFA.fs
VSharp.SILI/Interpreter.fs

Fix for reading field of struct, which is reference

Read struct field fix

---

VSharp.SILI.Core/InterpreterBase.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/MemoryRegion.fs
VSharp.SILI/InstructionsSet.fs
VSharp.SILI/Interpreter.fs
VSharp.Test/Tests/PDR.cs

- stackReading and heapReading now have zero time
- map for heapAddressKey works correctly

New memory model fixes

---

VSharp.API/VSharp.cs
VSharp.SILI.Core/API.fs

This partially fixes issue reported by @max-arshinov at discussion of #127. See the discussion for more details.

Enable test generation for constructors

---

VSharp.API/VSharp.cs
VSharp.Runner/RunnerProgram.cs
VSharp.SILI.Core/API.fs
VSharp.SILI.Core/API.fsi
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/Terms.fs
VSharp.SILI/BidirectionalSearcher.fs
VSharp.SILI/CILState.fs
VSharp.SILI/DistanceWeighter.fs
VSharp.SILI/Options.fs
VSharp.SILI/SILI.fs
VSharp.SILI/Searcher.fs
VSharp.SILI/Statistics.fs
VSharp.SILI/TargetedSearcher.fs
VSharp.Solver/Z3.fs
VSharp.Test/IntegrationTests.cs
VSharp.Utils/TypeUtils.fs

Also includes:
- timeouts
- branch releases
- fix for decimals

Shortest distance based searcher

---

VSharp.API/VSharp.cs
VSharp.IL/CFG.fs
VSharp.IL/CallGraph.fs
VSharp.IL/DotVisualizer.fs
VSharp.IL/ILRewriter.fs
VSharp.IL/MethodBody.fs
VSharp.IL/VSharp.IL.fsproj
VSharp.SILI.Core/API.fs
VSharp.SILI.Core/API.fsi
VSharp.SILI.Core/CallStack.fs
VSharp.SILI/BidirectionalSearcher.fs
VSharp.SILI/CILState.fs
VSharp.SILI/Interpreter.fs
VSharp.SILI/Options.fs
VSharp.SILI/SILI.fs
VSharp.Test/IntegrationTests.cs
VSharp.Utils/Reflection.fs

Visualizes the execution process like this:
+ Makes one snapshot in basic block transition or state forking
+ Grey nodes (edges) are visited basic blocks (transitions), 
+ Nodes with states are purple; darker purple means more states standing at this node

Graphviz coverage visualizer

---

VSharp.IL/CFG.fs
VSharp.IL/ILRewriter.fs
VSharp.IL/MethodBody.fs
VSharp.IL/VSharp.IL.fsproj
VSharp.InternalCalls/Loader.fs
VSharp.InternalCalls/SR.fs
VSharp.InternalCalls/SR.fsi
VSharp.SILI/ClientMachine.fs
VSharp.SILI/Instrumenter.fs
VSharp.SILI/Interpreter.fs
VSharp.Solver/Z3.fs
VSharp.Test/Tests/ControlFlow.cs
VSharp.Test/Tests/Lists.cs
VSharp.Utils/Collections.fs
VSharp.Utils/MemoryGraph.fs
VSharp.Utils/Reflection.fs
VSharp.Utils/TypeUtils.fs

- internal calls integrated into 'Method' class
- bug fixes
- enums encoding to Z3 solver
- style fixes
- added internal calls

Stabilization and internal calls integration into 'Method'

---

VSharp.SILI.Core/API.fs
VSharp.SILI.Core/API.fsi
VSharp.SILI.Core/TypeSolver.fs
VSharp.SILI/SILI.fs
VSharp.Test/Tests/GenericStructs.cs
VSharp.Utils/Reflection.fs
VSharp.Utils/TestResultsChecker.fs
VSharp.Utils/UnitTest.fs

- Pass types with substituted parameters to MemoryGraph
- Try solve generic parameters before execution

[fix] Generic parameters substitution

---

VSharp.Test/Tests/ControlFlow.cs
VSharp.TestExtensions/Allocator.cs
VSharp.TestExtensions/ObjectsComaprer.cs
VSharp.TestExtensions/VSharp.TestExtensions.csproj
VSharp.TestRenderer/ClassRenderer.cs
VSharp.TestRenderer/CodeRenderer.cs
VSharp.TestRenderer/IdentifiersCache.cs
VSharp.TestRenderer/MethodRenderer.cs
VSharp.TestRenderer/RendererProgram.cs
VSharp.TestRenderer/RendererTool.cs
VSharp.TestRenderer/VSharp.TestRenderer.csproj
VSharp.TestRunner/TestRunnerTool.cs
VSharp.TestRunner/VSharp.TestRunner.csproj
VSharp.Utils/MemoryGraph.fs
VSharp.Utils/Reflection.fs
VSharp.Utils/TestResultsChecker.fs
VSharp.Utils/UnitTest.fs
VSharp.sln

- Added NUnit test generation
- Added TestExtensions, which used in generated tests and TestRunner
- Mocks generation is still missing
- Future work: xUnit, pretty variables and test names, mocks

Pretty NUnit test generation

---

VSharp.IL/MethodBody.fs
VSharp.SILI/Interpreter.fs
VSharp.SILI/SILI.fs
VSharp.Test/Tests/Attributes.cs

https://ci.appveyor.com/project/misonijnik/vsharp/builds/44978538/tests

Chek NotNull attribute for return parameter

---

VSharp.CSharpUtils/MonitorUtils.cs
VSharp.InternalCalls/Loader.fs
VSharp.InternalCalls/SR.fs
VSharp.InternalCalls/SR.fsi
VSharp.SILI.Core/ConcreteMemory.fs
VSharp.SILI/Interpreter.fs
VSharp.TestExtensions/Allocator.cs
VSharp.TestRenderer/CodeRenderer.cs
VSharp.TestRenderer/MethodRenderer.cs
VSharp.TestRenderer/RendererTool.cs
VSharp.TestRunner/TestRunnerTool.cs
VSharp.Utils/PhysicalAddress.fs
VSharp.Utils/VSharp.Utils.fsproj

- supported ref/out parameters
- fixed get/set properties
- supported recursive data structures
- other fixes

Test generation improvements

---

VSharp.API/VSharp.cs
VSharp.CSharpUtils/VSharp.CSharpUtils.csproj
VSharp.TestRenderer/RendererTool.cs
VSharp.TestRenderer/VSharp.TestRenderer.csproj

- Changed API for Rider extension
- Microsoft.CodeAnalysis changed to JetBrains.Roslyn.References.Repack

Style fixes for integration into UTBot

---

VSharp.SILI/TargetedSearcher.fs

Fix dumb bug which has broken guided searcher completely in https://github.com/VSharp-team/VSharp/pull/171

[fix] Fix broken targeted searcher

---

.github/workflows/integration_tests.yml
.github/workflows/publish_docker.yml

Remove attempt to set autocancelling for irrelevant jobs

Fix broken CI

---

VSharp.SILI.Core/API.fs
VSharp.SILI.Core/API.fsi
VSharp.SILI.Core/Arithmetics.fs
VSharp.SILI.Core/ArrayInitialization.fs
VSharp.SILI.Core/Branching.fs
VSharp.SILI.Core/ConcreteMemory.fs
VSharp.SILI.Core/Copying.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/MemoryRegion.fs
VSharp.SILI.Core/Operations.fs
VSharp.SILI.Core/State.fs
VSharp.SILI.Core/Terms.fs
VSharp.SILI/Interpreter.fs
VSharp.SILI/TestGenerator.fs
VSharp.SILI/VSharp.SILI.fsproj
VSharp.Solver/Z3.fs
VSharp.Test/RegionTreeTests.cs
VSharp.Test/Tests/Lists.cs
VSharp.Test/VSharp.Test.csproj
VSharp.Utils/NumericUtils.fs
VSharp.Utils/PersistentDictionary.fs
VSharp.Utils/Regions.fs
VSharp.Utils/VSharp.Utils.fsproj

- changed array copy via adding array range key
- fixed points region comparison
- style fixes

Fixed copying arrays and fixes

---

VSharp.Runner/RunnerProgram.cs
VSharp.SILI.Core/Branching.fs
VSharp.SILI.Core/ConcreteMemory.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI/Interpreter.fs
VSharp.SILI/TestGenerator.fs
VSharp.Solver/Z3.fs
VSharp.Test/Tests/LinqTest.cs
VSharp.Test/Tests/Lists.cs

- Solver interaction fixes
- Efficiency fixes
- Style fixes
- New test

Stabilization: part I

---

VSharp.API/VSharp.cs
VSharp.CSharpUtils/VSharpAssemblyLoadContext.cs
VSharp.Runner/RunnerProgram.cs
VSharp.SILI.Core/TypeSolver.fs
VSharp.Test/IntegrationTests.cs
VSharp.Test/VSharpAssemblyLoadContextTests.cs
VSharp.TestRenderer/RendererTool.cs
VSharp.TestRunner/TestRunnerTool.cs
VSharp.Utils/AssemblyManager.fs
VSharp.Utils/MemoryGraph.fs
VSharp.Utils/Reflection.fs

#214 
Выкладываю текущую версию загрузчика на общее обсуждение. Нейминг и местоположение тех или иных методов можно обсудить
Интеграционные тесты работают. Бенчмарки смотрели с @MchKosticyn -- вроде всё хорошо

New single assembly loader

---

VSharp.SILI/Interpreter.fs
VSharp.SILI/SILI.fs
VSharp.Solver/Z3.fs
VSharp.Test/Tests/Lists.cs

- fixed https://github.com/VSharp-team/VSharp/issues/231
- fixed https://github.com/VSharp-team/VSharp/issues/238
- fixed Array.Copy bounds check

Stabilization: part III

---

VSharp.SILI.Core/Memory.fs
VSharp.SILI/TestGenerator.fs
VSharp.Solver/Z3.fs
VSharp.Test/Tests/Structs.cs

Stabilization: part V

---

VSharp.API/VSharp.cs
VSharp.CSharpUtils/VSharpAssemblyLoadContext.cs
VSharp.SILI.Core/Terms.fs
VSharp.SILI.Core/TypeSolver.fs
VSharp.Test/IntegrationTests.cs
VSharp.Test/Tests/Enums.cs
VSharp.Utils/AssemblyManager.fs
VSharp.Utils/EnumUtils.fs
VSharp.Utils/Mocking.fs

- Create mocks assembly in V# context
- Normalize methods passed via API
- Fix default value for enums without zero (fixes https://github.com/VSharp-team/VSharp/issues/192)

Stabilization: part VII

---

VSharp.CSharpUtils/VSharpAssemblyLoadContext.cs
VSharp.IL/MethodBody.fs
VSharp.InternalCalls/Environment.fs
VSharp.InternalCalls/Environment.fsi
VSharp.SILI.Core/API.fs
VSharp.SILI.Core/TypeSolver.fs
VSharp.SILI/Interpreter.fs
VSharp.Test/IntegrationTests.cs
VSharp.Test/Tests/Generic.cs
VSharp.Test/Tests/Mocking.cs
VSharp.TestRenderer/CodeRenderer.cs
VSharp.TestRenderer/MethodRenderer.cs
VSharp.TestRenderer/ProgramRenderer.cs
VSharp.TestRenderer/TypeRenderer.cs
VSharp.Utils/Reflection.fs
VSharp.Utils/TypeUtils.fs

- fixed usages of internalSizeOf with generic types
- added support of constructors in method normalization
- added support of rendering mocked indexers
- fixed solving method generic arguments in type solver
- fixed rendering nested generic types
- fixed style

Stabilization: Part IX

---

VSharp.SILI.Core/ConcreteMemory.fs
VSharp.SILI.Core/Terms.fs

- Fix stack overflows caused by intptr casting

Stabilization: part X

---

VSharp.API/DependencyResolver.cs
VSharp.API/VSharp.API.csproj
VSharp.CSharpUtils/ReflectionUtils.cs
VSharp.CSharpUtils/VSharpAssemblyLoadContext.cs
VSharp.SILI.Core/TypeSolver.fs
VSharp.Utils/AssemblyManager.fs

- Fix GetExportedTypes throwing exception in TypeSolver.enumerateTypes
- Add API for custom assembly resolving logic

Rider plugin fixes

---

VSharp.CSharpUtils/RuntimeHelpers.cs
VSharp.CSharpUtils/StringUtils.cs
VSharp.InternalCalls/Buffer.fs
VSharp.InternalCalls/Loader.fs
VSharp.InternalCalls/Span.fs
VSharp.InternalCalls/Span.fsi
VSharp.InternalCalls/String.fs
VSharp.InternalCalls/String.fsi
VSharp.InternalCalls/VSharp.InternalCalls.fsproj
VSharp.SILI.Core/API.fs
VSharp.SILI.Core/API.fsi
VSharp.SILI.Core/Arithmetics.fs
VSharp.SILI.Core/ConcreteMemory.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/Substitution.fs
VSharp.SILI.Core/Terms.fs
VSharp.SILI.Core/TypeCasting.fs
VSharp.SILI.Core/TypeSolver.fs
VSharp.SILI/Interpreter.fs
VSharp.SILI/TestGenerator.fs
VSharp.Test/Tests/Strings.cs
VSharp.TestRenderer/MethodRenderer.cs
VSharp.TestRenderer/TestsRenderer.cs
VSharp.Utils/MemoryGraph.fs
VSharp.Utils/Reflection.fs
VSharp.Utils/UnitTest.fs

- fixed renderer
- fixed internal calls
- fully implemented '.constrained' prefix
- fixed concrete memory
- fixed array reading composition
- fixed serialization of strings
- added new tests for strings
- style fixes

Stabilization: part XIII

---

VSharp.IL/CFG.fs
VSharp.IL/MethodBody.fs
VSharp.InternalCalls/Unsafe.fsi
VSharp.SILI/Interpreter.fs
VSharp.Test/Tests/LinqTest.cs
VSharp.TestGenerator/VSharp.TestGenerator.fsproj

- fixed 'fault' exception handling clause
- fixed style

Fixed exception handling clauses

---

VSharp.InternalCalls/Buffer.fs
VSharp.InternalCalls/Buffer.fsi
VSharp.InternalCalls/Enum.fs
VSharp.InternalCalls/Span.fs
VSharp.InternalCalls/Span.fsi
VSharp.InternalCalls/String.fs
VSharp.InternalCalls/Unsafe.fsi
VSharp.SILI.Core/API.fs
VSharp.SILI.Core/API.fsi
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/Pointers.fs
VSharp.SILI/Interpreter.fs

- added state branching for symbolic pointers
- fixed unsafe operations
- fixed span internal calls
- fixed reference checking

Stabilization: part XXIII

---

VSharp.IL/ILRewriter.fs
VSharp.IL/MethodBody.fs
VSharp.IL/VSharp.IL.fsproj
VSharp.InternalCalls/VSharp.InternalCalls.fsproj
VSharp.SILI.Core/API.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/State.fs
VSharp.SILI.Core/VSharp.SILI.Core.fsproj
VSharp.SILI/CILState.fs
VSharp.SILI/InstructionPointer.fs
VSharp.SILI/Interpreter.fs
VSharp.SILI/VSharp.SILI.fsproj
VSharp.SVM/BidirectionalSearcher.fs
VSharp.SVM/DistanceWeighter.fs
VSharp.SVM/GuidedSearcher.fs
VSharp.SVM/Statistics.fs
VSharp.SVM/VSharp.SVM.fsproj
VSharp.Solver/VSharp.Solver.fsproj
VSharp.Test/Tests/ControlFlow.cs
VSharp.Test/Tests/ExceptionsControlFlow.cs
VSharp.TestExtensions/VSharp.TestExtensions.csproj
VSharp.TestGenerator/TestGenerator.fs
VSharp.TestGenerator/VSharp.TestGenerator.fsproj
VSharp.TestRenderer/RendererTool.cs
VSharp.Utils/TypeUtils.fs
VSharp.Utils/VSharp.Utils.fsproj

- fixed exception handling
- fixed 'FSharp.Core' version

Stabilization: part XXVI

---

VSharp.IL/Loader.fs
VSharp.SILI.Core/CallStack.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/State.fs
VSharp.Solver/Z3.fs
VSharp.Test/Tests/Arithmetics.cs
VSharp.Test/Tests/Lambdas.cs
VSharp.Test/Tests/Lists.cs
VSharp.Test/Tests/RegExTest.cs
VSharp.Test/Tests/Typecast.cs
VSharp.Test/Tests/Unsafe.cs
VSharp.Utils/Collections.fs

- implemented encoding of floating point numbers into Z3

Encoding of floating point numbers

---

VSharp.SILI.Core/API.fs
VSharp.SILI.Core/Arithmetics.fs
VSharp.SILI.Core/Memory.fs
VSharp.SILI.Core/MemoryRegion.fs
VSharp.SILI.Core/Merging.fs
VSharp.SILI.Core/Pointers.fs
VSharp.SILI.Core/TypeCasting.fs
VSharp.Solver/Z3.fs
VSharp.Utils/RegionTree.fs
VSharp.Utils/VectorTime.fs

Move keys match condition from `Z3.fs` to `MemoryRegion.fs` in order to use it in Splitting

Keys match condition

---

VSharp.IL/Loader.fs
VSharp.InternalCalls/Span.fs
VSharp.SILI.Core/API.fs
VSharp.SILI.Core/API.fsi
VSharp.SILI.Core/SolverInteraction.fs
VSharp.SILI.Core/TypeCasting.fs
VSharp.SILI.Core/TypeSolver.fs
VSharp.SILI.Core/TypeSolverUtils.fs
VSharp.SILI/Interpreter.fs
VSharp.Solver/Z3.fs
VSharp.Test/Tests/Generic.cs
VSharp.Test/Tests/Lists.cs
VSharp.Test/Tests/Strings.cs
VSharp.Test/UtilsTests.cs

- added equality constraint for virtual call dispatch

Type sovler fixes

---

VSharp.CSharpUtils/EnvironmentUtils.cs
VSharp.CSharpUtils/JetBrainsDiagnosticsUtils.cs
VSharp.IL/Loader.fs
VSharp.SILI/CILState.fs
VSharp.Test/Tests/InternalCalls.cs
VSharp.Test/Tests/Lists.cs
VSharp.TestRenderer/TestsRenderer.cs
VSharp.Utils/Copier.fs
VSharp.Utils/UnitTest.fs

- fixed renderer
- fixed deserialization of unit test
- fixed deep copy
- added test

Stabilization: part XXIX
